FROM opensuse/leap:16.1

WORKDIR /app

RUN zypper --non-interactive install \
        python3 \
        python3-pip \
    && zypper clean --all

COPY dist/fortune_technical_interwiew_task-0.0.1-py3-none-any.whl .

RUN pip3 install --no-cache-dir \
        fortune_technical_interwiew_task-0.0.1-py3-none-any.whl

EXPOSE 8000

CMD ["python3", "-m", "fortune"]