FROM python:3.12-slim

WORKDIR /app

COPY dist/fortune_technical_interwiew_task-0.0.1-py3-none-any.whl .

RUN pip install --no-cache-dir fortune_technical_interwiew_task-0.0.1-py3-none-any.whl

EXPOSE 8000

CMD ["python", "-m", "fortune"]